apiVersion: v1
kind: Service
metadata:
  name: storage-nfs-server-provisioner
  labels:
    app: nfs-server-provisioner
spec:
  ports:
  - name: nfs
    port: 2049
    protocol: TCP
    targetPort: nfs
  - name: mountd
    port: 20048
    protocol: TCP
    targetPort: mountd
  - name: rpcbind-tcp
    port: 51413
    protocol: TCP
    targetPort: rpcbind-tcp
  - name: rpcbind-udp
    port: 51413
    protocol: UDP
    targetPort: rpcbind-udp
  selector:
    app: nfs-server-provisioner
  type: ClusterIP
