apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: storage-nfs-server-provisioner
  labels:
    app: nfs-server-provisioner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-server-provisioner
  serviceName: storage-nfs-server-provisioner
  template:
    metadata:
      labels:
        app: nfs-server-provisioner
    spec:
      # NOTE: This is 10 seconds longer than the default nfs-provisioner --grace-period value of 90sec
      terminationGracePeriodSeconds: 100
      serviceAccountName: storage-nfs-server-provisioner
      containers:
        - name: nfs-server-provisioner
          image: quay.io/kubernetes_incubator/nfs-provisioner #:v1.0.9
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 2049
            name: nfs
            protocol: TCP
          - containerPort: 20048
            name: mountd
            protocol: TCP
          - containerPort: 111
            name: rpcbind-tcp
            protocol: TCP
          - containerPort: 111
            name: rpcbind-udp
            protocol: UDP
          securityContext:
            capabilities:
              add:
              - DAC_READ_SEARCH
              - SYS_RESOURCE
          args:
            - -provisioner=cluster.local/storage-nfs-server-provisioner
          env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: SERVICE_NAME
            value: storage-nfs-server-provisioner
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          volumeMounts:
          - mountPath: /export
            name: data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Gi
